name: Build and deploy Python app to Azure Web App - krishilekha

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libsndfile1 \
            build-essential \
            cmake \
            libopenblas-dev \
            libomp-dev \
            git \
            wget \
            unzip \
            libx11-dev \
            libgl1 \
            poppler-utils \
            libreadline-dev \
            libssl-dev \
            zlib1g-dev \
            libffi-dev \
            libbz2-dev \
            liblzma-dev \
            libsqlite3-dev

      - name: Install latest SQLite (>=3.35.0)
        run: |
          wget https://www.sqlite.org/2023/sqlite-autoconf-3420000.tar.gz
          tar xzf sqlite-autoconf-3420000.tar.gz
          cd sqlite-autoconf-3420000
          ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make install
          cd ..
          echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/sqlite3.conf
          sudo ldconfig

      - name: Verify SQLite version
        run: |
          /usr/local/bin/sqlite3 --version

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install Python dependencies
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          source venv/bin/activate
          playwright install --with-deps

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r -x venv/\*

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A5F2D738D99C4E54A7D4C9192A4B3A21 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A11025F539E43ACB8C0FC0283F03CB9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EA3CA12FCAF4460F84DF3BBB3CA50789 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'krishilekha'
          slot-name: 'Production'
